[2024-09-12T09:18:51.176+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-12T09:18:51.203+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v21.insert_orders_data scheduled__2024-09-10T00:00:00+00:00 [queued]>
[2024-09-12T09:18:51.218+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v21.insert_orders_data scheduled__2024-09-10T00:00:00+00:00 [queued]>
[2024-09-12T09:18:51.298+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-12T09:18:51.350+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_orders_data> on 2024-09-10 00:00:00+00:00
[2024-09-12T09:18:51.359+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v21', 'insert_orders_data', 'scheduled__2024-09-10T00:00:00+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp8sbs3jxf']
[2024-09-12T09:18:51.361+0000] {standard_task_runner.py:105} INFO - Job 442: Subtask insert_orders_data
[2024-09-12T09:18:51.362+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1789) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T09:18:51.363+0000] {standard_task_runner.py:72} INFO - Started process 1794 to run task
[2024-09-12T09:18:51.438+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v21.insert_orders_data scheduled__2024-09-10T00:00:00+00:00 [running]> on host 72ac4976c45d
[2024-09-12T09:18:51.570+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v21' AIRFLOW_CTX_TASK_ID='insert_orders_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-10T00:00:00+00:00'
[2024-09-12T09:18:51.572+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-12T09:18:51.583+0000] {sql.py:266} INFO - Executing: 
            COPY orders(customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        
[2024-09-12T09:18:51.596+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-12T09:18:51.689+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-12T09:18:51.708+0000] {sql.py:509} INFO - Running statement: 
            COPY orders(customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        , parameters: None
[2024-09-12T09:18:51.716+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY orders, line 2: "1,500,275,7/20/2024,44.434"

[2024-09-12T09:18:51.735+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag_v21, task_id=insert_orders_data, run_id=scheduled__2024-09-10T00:00:00+00:00, execution_date=20240910T000000, start_date=20240912T091851, end_date=20240912T091851
[2024-09-12T09:18:51.778+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-12T09:18:51.779+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 442 for task insert_orders_data (extra data after last expected column
CONTEXT:  COPY orders, line 2: "1,500,275,7/20/2024,44.434"
; 1794)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.BadCopyFileFormat: extra data after last expected column
CONTEXT:  COPY orders, line 2: "1,500,275,7/20/2024,44.434"

[2024-09-12T09:18:51.820+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-12T09:18:51.840+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T09:18:51.844+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
