[2024-09-20T07:43:29.695+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T07:43:29.720+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v39.insert_inventory_data manual__2024-09-20T07:29:43.600502+00:00 [queued]>
[2024-09-20T07:43:29.736+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v39.insert_inventory_data manual__2024-09-20T07:29:43.600502+00:00 [queued]>
[2024-09-20T07:43:29.737+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 6
[2024-09-20T07:43:29.774+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_inventory_data> on 2024-09-20 07:29:43.600502+00:00
[2024-09-20T07:43:29.786+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v39', 'insert_inventory_data', 'manual__2024-09-20T07:29:43.600502+00:00', '--job-id', '1106', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmprekcoti1']
[2024-09-20T07:43:29.788+0000] {standard_task_runner.py:105} INFO - Job 1106: Subtask insert_inventory_data
[2024-09-20T07:43:29.790+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1017) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-20T07:43:29.791+0000] {standard_task_runner.py:72} INFO - Started process 1022 to run task
[2024-09-20T07:43:29.864+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v39.insert_inventory_data manual__2024-09-20T07:29:43.600502+00:00 [running]> on host 217a74bc1b7d
[2024-09-20T07:43:29.994+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v39' AIRFLOW_CTX_TASK_ID='insert_inventory_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T07:29:43.600502+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-20T07:29:43.600502+00:00'
[2024-09-20T07:43:29.995+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T07:43:30.007+0000] {sql.py:266} INFO - Executing: 
            TRUNCATE TABLE inventory;
            COPY inventory(id, name, stock_quantity, price)
            FROM '/shared/inventory.csv'
            DELIMITER ',' CSV HEADER;
        
[2024-09-20T07:43:30.023+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-20T07:43:30.109+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-20T07:43:30.125+0000] {sql.py:509} INFO - Running statement: 
            TRUNCATE TABLE inventory;
            COPY inventory(id, name, stock_quantity, price)
            FROM '/shared/inventory.csv'
            DELIMITER ',' CSV HEADER;
        , parameters: None
[2024-09-20T07:43:30.130+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.FeatureNotSupported: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "order_lists" references "inventory".
HINT:  Truncate table "order_lists" at the same time, or use TRUNCATE ... CASCADE.

[2024-09-20T07:43:30.147+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag_v39, task_id=insert_inventory_data, run_id=manual__2024-09-20T07:29:43.600502+00:00, execution_date=20240920T072943, start_date=20240920T074329, end_date=20240920T074330
[2024-09-20T07:43:30.202+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T07:43:30.215+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1106 for task insert_inventory_data (cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "order_lists" references "inventory".
HINT:  Truncate table "order_lists" at the same time, or use TRUNCATE ... CASCADE.
; 1022)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.FeatureNotSupported: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "order_lists" references "inventory".
HINT:  Truncate table "order_lists" at the same time, or use TRUNCATE ... CASCADE.

[2024-09-20T07:43:30.248+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-20T07:43:30.267+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T07:43:30.269+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
