[2024-09-20T16:26:10.152+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T16:26:10.177+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag_v44.insert_orders_data scheduled__2024-09-19T00:00:00+00:00 [queued]>
[2024-09-20T16:26:10.196+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag_v44.insert_orders_data scheduled__2024-09-19T00:00:00+00:00 [queued]>
[2024-09-20T16:26:10.197+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 6
[2024-09-20T16:26:10.236+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_orders_data> on 2024-09-19 00:00:00+00:00
[2024-09-20T16:26:10.245+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag_v44', 'insert_orders_data', 'scheduled__2024-09-19T00:00:00+00:00', '--job-id', '1577', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp6pr4hs6_']
[2024-09-20T16:26:10.247+0000] {standard_task_runner.py:105} INFO - Job 1577: Subtask insert_orders_data
[2024-09-20T16:26:10.249+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5700) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-20T16:26:10.250+0000] {standard_task_runner.py:72} INFO - Started process 5705 to run task
[2024-09-20T16:26:10.335+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag_v44.insert_orders_data scheduled__2024-09-19T00:00:00+00:00 [running]> on host 217a74bc1b7d
[2024-09-20T16:26:10.477+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag_v44' AIRFLOW_CTX_TASK_ID='insert_orders_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-19T00:00:00+00:00'
[2024-09-20T16:26:10.479+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T16:26:10.489+0000] {sql.py:266} INFO - Executing: 
            TRUNCATE TABLE order_lists;
            COPY order_lists(id, customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        
[2024-09-20T16:26:10.504+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-20T16:26:10.576+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-20T16:26:10.595+0000] {sql.py:509} INFO - Running statement: 
            TRUNCATE TABLE order_lists;
            COPY order_lists(id, customer_id, product_id, order_date, quantity)
            FROM '/shared/orders.csv'
            DELIMITER ',' CSV HEADER;
        , parameters: None
[2024-09-20T16:26:10.617+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.ForeignKeyViolation: insert or update on table "order_lists" violates foreign key constraint "fk_product"
DETAIL:  Key (product_id)=(107) is not present in table "inventory".

[2024-09-20T16:26:10.634+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag_v44, task_id=insert_orders_data, run_id=scheduled__2024-09-19T00:00:00+00:00, execution_date=20240919T000000, start_date=20240920T162610, end_date=20240920T162610
[2024-09-20T16:26:10.683+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T16:26:10.684+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 1577 for task insert_orders_data (insert or update on table "order_lists" violates foreign key constraint "fk_product"
DETAIL:  Key (product_id)=(107) is not present in table "inventory".
; 5705)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.ForeignKeyViolation: insert or update on table "order_lists" violates foreign key constraint "fk_product"
DETAIL:  Key (product_id)=(107) is not present in table "inventory".

[2024-09-20T16:26:10.706+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-20T16:26:10.728+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T16:26:10.730+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
